server:
    port: '${PORT:8082}'
    
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        server:
            waitTimeInMsWhenSyncEmpty: 0
        serviceUrl:
          defaultZone : 'http://localhost:8761/eureka/'

        
